name = "kecc-business-flow"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# Use npm instead of bun for more reliable CI/CD
[build]
command = "npm ci && npm run build"

[env.production.vars]
ENVIRONMENT = "production"
VITE_APP_ENV = "production"

[env.preview.vars]
ENVIRONMENT = "preview"
VITE_APP_ENV = "preview"
