name = "kecc-business-flow"
compatibility_date = "2025-07-02"

[assets]
not_found_handling = "single-page-application"

[env.production]
name = "kecc-business-flow-production"

[env.production.vars]
ENVIRONMENT = "production"
VITE_APP_ENV = "production"

[env.preview]
name = "kecc-business-flow-preview"

[env.preview.vars]
ENVIRONMENT = "preview"
VITE_APP_ENV = "preview"
