name = "kecc-business-flow"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"
node_compat = true

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[env.production]
compatibility_date = "2024-01-01"

[env.preview]
compatibility_date = "2024-01-01"