// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhiazztknwacdkzmgrci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJoaWF6enRrbndhY2Rrem1ncmNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NTY2NTQsImV4cCI6MjA1OTUzMjY1NH0.SFo1EVuTwrP8dkUZzKeupfO5mrQhur101jvcrKBR680";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);